services:
#  server:
#    container_name: server
#    build:
#      context: ./server
#    volumes:
#      - ./server:/server
#      - ./server/node_modules:/server/node_modules
#    command: npm run start:dev
#    depends_on:
#      - postgres
#    restart: always
#    ports:
#      - 5000:5000

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./server/.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: